version: 2
open-pull-requests-limit: 8

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: weekly
